### ISSUE TITLE
Code updated but version number remains the same.

### ISSUE THREAD

**Issue by simondrabble** [riggerthegeek/ng-page-title#10]
Looks like the addition of support for ui-router^1.0.0 should have resulted in a version bump, however, from NPM:

```
/*!
 * ng-page-title
 *
 * @author Simon Emms <simon@simonemms.com>
 * @build 2016-08-05T16:39:46
 * @description Page title directive for an Angular project
 * @license MIT
 * @version v1.3.1
 */
```

(note the build date)

and from the current (as of this ticket) code:

```
/*!
 * ng-page-title
 *
 * @author Simon Emms <simon@simonemms.com>
 * @build 2017-07-03T23:31:31
 * @description Page title directive for an Angular project
 * @license MIT
 * @version v1.3.1
 */
```

i.e. updated a couple of months ago, but the version was not updated. Practically speaking this means the package cannot be reliably used from NPM.

**Comment by riggerthegeek** [comment]
I'm no longer supporting this module. If you want to take over this, I can transfer you ownership of this and the npm module
