### ISSUE TITLE
Any way to make this work with named views?

### ISSUE THREAD

**Issue by benjamincharity** [riggerthegeek/ng-page-title#4]
It seems that this works perfectly with standard views and nested views, but when dealing with named views, no title is set.

```javascript
.state('merchants.merchant', {
    url: '/:merchantId',
    views: {
        '': {
            templateUrl: 'app/merchants/merchant/merchant.html',
            controller: 'MerchantController as vm',
            resolve: {
                merchant: function(MerchantService, $stateParams) {
                    if ($stateParams.merchantId) {
                        return MerchantService.getMerchant($stateParams.merchantId);
                    }
                },
            },
            data: {
                pageTitle: 'TEST',
            },
        },
        locations: {
            templateUrl: 'app/merchants/merchant/merchant.locations.html',
            controller: 'LocationsController as vm',
            resolve: {
                locations: function(MerchantService, $stateParams) {
                    if ($stateParams.merchantId) {
                        return MerchantService.getLocations($stateParams.merchantId);
                    }
                },
            },
        },
    },
})
```

In this case, the title `TEST` will never be used. Any ideas on this?

**Comment by riggerthegeek** [comment]
Hmmmmm...

I must confess, I've never had the need to put it on a named view. If you look at the [source code](https://github.com/riggerthegeek/ng-page-title/blob/master/src/directive/stateTitle.js#L33), the data element is specifically looking at the whole of the state, not a specific view.

If you want to have a hack and submit a pull request, I think this would be a good addition to the package

**Comment by riggerthegeek** [comment]
Having looked back at this issue, I'm going to have to back it out. It's not kept compatibility with the existing functionality.

Feel free to resubmit this, but please make sure that the existing functionality is retained. I've kept this as v1.2.0 and it's on `feature/named-views` branch.

A new version `v1.3.0` is being created with the existing functionality

**Comment by benjamincharity** [comment]
What functionality is missing?

**Comment by riggerthegeek** [comment]
You pull request only works with named views. If you have the `data` in the main part of the route as before, it doesn't work.

**Comment by benjamincharity** [comment]
Interesting.. I'm currently using it on named and un-named views. I'll take another look and see if I can sort it out.
