### ISSUE TITLE
Resolve data asynchronously for dynamic title

### ISSUE THREAD

**Issue by waynechaw** [riggerthegeek/ng-page-title#6]
As of now, data has to be returned synchronously for the pageTitle data. is there a way to make an ajax call from resolve and display title dynamically based on result?

**Comment by riggerthegeek** [comment]
Yes. The resolve waits until a promise is resolved before it renders the state. The UI Router docs cover this comprehensively

**Comment by waynechaw** [comment]
This is what I have tried unsuccessfully:

myApp.config(function ($stateProvider) {
    $stateProvider
        .state("article", {
            data: {
                pageTitle: "Article: {{ article.getTitle() }}"
            },
            resolve: {
                article: function ($http) {
                 return {
                        getTitle: function () {
                            return $http({method: 'GET', url: '/someUrl'}).then(function(response){
                                return response.value;
                            })
                        }
                    };
                }
            },
            url: "/article/:name",
            templateUrl: "partials/article.html"
        });
}

**Comment by waynechaw** [comment]
`This is what I have tried unsuccessfully:

myApp.config(function ($stateProvider) {
    $stateProvider
        .state("article", {
            data: {
                pageTitle: "Article: {{ article.getTitle() }}"
            },
            resolve: {
                article: function ($http) {
                 return {
                        getTitle: function () {
                            return $http({method: 'GET', url: '/someUrl'}).then(function(response){
                                return response.value;
                            })
                        }
                    };
                }
            },
            url: "/article/:name",
            templateUrl: "partials/article.html"
        });
}`

**Comment by waynechaw** [comment]
This is what I have tried unsuccessfully, please advise

```
myApp.config(function ($stateProvider) {
    $stateProvider
        .state("article", {
            data: {
                pageTitle: "Article: {{ article.getTitle() }}"
            },
            resolve: {
                article: function ($http) {
                 return {
                        getTitle: function () {
                            return $http({method: 'GET', url: '/someUrl'}).then(function(response){
                                return response.value;
                            })
                        }
                    };
                }
            },
            url: "/article/:name",
            templateUrl: "partials/article.html"
        });
}
```

**Comment by riggerthegeek** [comment]
You've not got any UI Router views set up. Please check their docs.

Please let me know what you get in any future stuff. Just seeing the config is fine, but it doesn't let me know any errors you're receiving or why it's different to what you expect

**Comment by riggerthegeek** [comment]
Try using v1.1.1

Also, without knowing what you're getting, it's a bit hard to help just from reading your config

**Comment by waynechaw** [comment]
thanks for the response. I am using UI router. if my resolve function returns a value, similar to the example in the documentation

```
                        getTitle: function () {
                            return "Article Title"
                        }
```

then my page title will get that value. so it seems like it just cant get the data from a promise.

**Comment by riggerthegeek** [comment]
I've noticed a fuck-up in v1.2.x which I'm deprecating and about to publish v1.3.0 which is identical to v1.1.1. This works as per the docs.

Does using v1.1.1 solve your problem?

**Comment by waynechaw** [comment]
Just tried 1.1.1 and 1.3, neither solves the issue.

**Comment by riggerthegeek** [comment]
Ok.  Well, if you could explain:
 - what you're expecting and
 - what you're getting

I'll be able to help

**Comment by waynechaw** [comment]
```
myApp.config(function ($stateProvider) {
    $stateProvider
        .state("article", {
            data: {
                pageTitle: "Article: {{ article.getTitle() }}"
            },
            resolve: {
                article: function ($http) {
                 return {
                        getTitle: function () {
                            return $http({method: 'GET', url: '/someUrl'}).then(function(response){
                                return response.value;
                            })
                        }
                    };
                }
            },
            url: "/article/:name",
            templateUrl: "partials/article.html"
        });
}

```

above is the full code

```
                            return $http({method: 'GET', url: '/someUrl'}).then(function(response){
                                return response.value;
                            })
```

I expect response.value to be a string like "hello world", so I expect my page title to be "Article: hello world".

If I changed my code to:

```
                        getTitle: function () {
                            return "hola"
                        }
```

My page title would be "Article: hola". This is successful, only when I try to return a promise, it is unsuccessful.

**Comment by riggerthegeek** [comment]
Right, now I see what's going on.

The `pageTitle` is treated the same as a template file so must be synchronous.  By all means use a promise in the resolve, but what is then called in the `getTitle` method must be synchronous.

I use the `resolve` to populate a data model and then pass that into the template.  Ie, something like this

```
resolve: {
    article: ($http) {
         return $http({method: 'GET', url: '/someUrl'}).then(function(response){
             return {
                  getTitle: function () {
                      return response.value;
                  }
             };
         })
    }
}
```

**Comment by waynechaw** [comment]
amazing! that worked, thank you so much
